### ISSUE TITLE
include RapidJSON

### ISSUE THREAD

**Issue by mtmiller** [flathub/org.octave.Octave#220]
Add a RapidJSON module to compile the native JSON parser/generator in Octave version 7.

**Comment by Alexander-Wilms** [comment]
I added the following module, but Octave's ./configure step failed:

```yaml
  - name: rapidjson
    buildsystem: cmake-ninja
    sources:
      - type: archive
        url: https://github.com/Tencent/rapidjson/archive/refs/tags/v1.1.0.tar.gz
        sha256: bf7ced29704a1e696fbccf2a2b4ea068e7774fa37f6d7dd4039d0787f8bed98e
        x-checker-data:
          type: anitya
          project-id: 7422
          url-template: https://github.com/Tencent/rapidjson/archive/refs/tags/v$version.tar.gz
      - type: shell
        commands:
          # https://github.com/Tencent/rapidjson/issues/2017#issuecomment-1160818211
          - sed -e 's|-Werror||' -i CMakeLists.txt
          - sed -e 's|-Werror||' -i example/CMakeLists.txt
```


```
configure:80506: checking for rapidjson/rapidjson.h
configure:80506: g++ -c -O2 -g -pipe -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong -grecord-gcc-switches -pthread -fopenmp  conftest.cpp >&5
configure:80506: $? = 0
configure:80506: result: yes
configure:80527: checking for working PrettyWriter in RapidJSON
configure:80559: g++ -c -O2 -g -pipe -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong -grecord-gcc-switches -pthread -fopenmp  conftest.cpp >&5
In file included from conftest.cpp:511:
/app/include/rapidjson/prettywriter.h: In constructor 'rapidjson::PrettyWriter<OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags>::PrettyWriter(OutputStream&, StackAllocator*, std::size_t) [with OutputStream = rapidjson::GenericStringBuffer<rapidjson::UTF8<> >; SourceEncoding = rapidjson::UTF8<>; TargetEncoding = rapidjson::UTF8<>; StackAllocator = rapidjson::CrtAllocator; unsigned int writeFlags = 2; std::size_t = long unsigned int]':
/app/include/rapidjson/prettywriter.h:53:102: error: 'const std::size_t rapidjson::Writer<rapidjson::GenericStringBuffer<rapidjson::UTF8<> > >::kDefaultLevelDepth' is protected within this context
   53 |     explicit PrettyWriter(OutputStream& os, StackAllocator* allocator = 0, size_t levelDepth = Base::kDefaultLevelDepth) :
      |                                                                                                      ^~~~~~~~~~~~~~~~~~
In file included from /app/include/rapidjson/prettywriter.h:18:
/app/include/rapidjson/writer.h:262:25: note: declared protected here
  262 |     static const size_t kDefaultLevelDepth = 32;
      |                         ^~~~~~~~~~~~~~~~~~
conftest.cpp:528:77: note:   when instantiating default argument for call to 'rapidjson::PrettyWriter<OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags>::PrettyWriter(OutputStream&, StackAllocator*, std::size_t) [with OutputStream = rapidjson::GenericStringBuffer<rapidjson::UTF8<> >; SourceEncoding = rapidjson::UTF8<>; TargetEncoding = rapidjson::UTF8<>; StackAllocator = rapidjson::CrtAllocator; unsigned int writeFlags = 2; std::size_t = long unsigned int]'
  528 |                                 rapidjson::kWriteNanAndInfFlag> writer (json);
      |                                                                             ^
/app/include/rapidjson/prettywriter.h: In instantiation of 'rapidjson::PrettyWriter<OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags>::PrettyWriter(OutputStream&, StackAllocator*, std::size_t) [with OutputStream = rapidjson::GenericStringBuffer<rapidjson::UTF8<> >; SourceEncoding = rapidjson::UTF8<>; TargetEncoding = rapidjson::UTF8<>; StackAllocator = rapidjson::CrtAllocator; unsigned int writeFlags = 2; std::size_t = long unsigned int]':
conftest.cpp:528:77:   required from here
/app/include/rapidjson/prettywriter.h:54:110: error: type 'rapidjson::Writer<rapidjson::GenericStringBuffer<rapidjson::UTF8<> > >' is not a direct base of 'rapidjson::PrettyWriter<rapidjson::GenericStringBuffer<rapidjson::UTF8<> >, rapidjson::UTF8<>, rapidjson::UTF8<>, rapidjson::CrtAllocator, 2>'
   54 |         Base(os, allocator, levelDepth), indentChar_(' '), indentCharCount_(4), formatOptions_(kFormatDefault) {}
      |                     
```

Cf. https://github.com/Tencent/rapidjson/issues/1338#issuecomment-449850617

[config.log](https://github.com/flathub/org.octave.Octave/files/10911046/config.log)
